# Site settings
title: Travel blog
email: ahmadalkassar@gmail.com
description: My first blog.
baseurl: "/travel-blog"
twitter_username: 
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ahmad" # Set default author name
      categories: "Places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
